## Scaler Operation 

In [1]:
import dask.array as da

In [3]:
my_arr = da.random.randint(10 , size = 20 , chunks = 3)

In [7]:
my_arr

dask.array<randint, shape=(20,), dtype=int32, chunksize=(3,), chunktype=numpy.ndarray>

In [ ]:
my_arr.compute()

In [6]:
my_arr_hundred = my_arr+100
my_arr_hundred.compute()

array([106, 108, 107, 108, 104, 100, 109, 108, 101, 102, 101, 104, 106,
       103, 109, 100, 102, 102, 107, 109])

In [8]:
(my_arr*(-1)).compute()

array([-6, -8, -7, -8, -4,  0, -9, -8, -1, -2, -1, -4, -6, -3, -9,  0, -2,
       -2, -7, -9])

### Reduction 

In [10]:
dask_sum = my_arr.sum()
dask_sum

dask.array<sum-aggregate, shape=(), dtype=int32, chunksize=(), chunktype=numpy.ndarray>

In [11]:
my_arr.compute()

array([6, 8, 7, 8, 4, 0, 9, 8, 1, 2, 1, 4, 6, 3, 9, 0, 2, 2, 7, 9])

In [13]:
dask_sum.compute()

96

In [14]:
my_ones_arr = da.ones((10, 10), chunks = 2 , dtype = int)

In [15]:
my_ones_arr.compute()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
my_ones_arr.mean(axis = 0).compute()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
my_custom_array = da.random.randint(10 , size =(4,4), chunks = (1,4))

In [19]:
my_custom_array.compute()

array([[5, 8, 3, 2],
       [9, 9, 7, 3],
       [6, 3, 5, 2],
       [6, 5, 7, 0]])

In [20]:
my_custom_array.mean(axis = 0).compute()

array([6.5 , 6.25, 5.5 , 1.75])

In [21]:
my_custom_array.mean(axis = 1).compute()

array([4.5, 7. , 4. , 4.5])

## Slicing  

In [23]:
my_custom_array[1:3, 2:4]

dask.array<getitem, shape=(2, 2), dtype=int32, chunksize=(1, 2), chunktype=numpy.ndarray>

In [24]:
my_custom_array[1:3, 2:4].compute()

array([[7, 3],
       [5, 2]])

### Broadcasting


In [25]:
my_custom_array.compute()

array([[5, 8, 3, 2],
       [9, 9, 7, 3],
       [6, 3, 5, 2],
       [6, 5, 7, 0]])

In [27]:
my_small_arr= da.ones(4, chunks = 2)
my_small_arr.compute()

array([1., 1., 1., 1.])

In [28]:
brd_example1 = da.add(my_custom_array , my_small_arr)

In [29]:
brd_example1.compute()

array([[ 6.,  9.,  4.,  3.],
       [10., 10.,  8.,  4.],
       [ 7.,  4.,  6.,  3.],
       [ 7.,  6.,  8.,  1.]])

In [40]:
ten_arr = da.full_like(my_small_arr , 10)

In [41]:
ten_arr.compute()

array([10., 10., 10., 10.])

In [42]:
brd_example2= da.full_like(my_custom_arr, 10)

In [43]:
brd_example2.compute()

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## Reshaping 

In [30]:
my_custom_array.shape

(4, 4)

In [31]:
custom_array_1d = my_custom_array.reshape(16)

In [32]:
custom_array_1d

dask.array<reshape, shape=(16,), dtype=int32, chunksize=(4,), chunktype=numpy.ndarray>

In [33]:
custom_array_1d.compute()

array([5, 8, 3, 2, 9, 9, 7, 3, 6, 3, 5, 2, 6, 5, 7, 0])

###  Stacking

In [44]:
stacked_arr = da.stack([brd_example1 , brd_example2])

In [45]:
stacked_arr.compute()

array([[[ 6.,  9.,  4.,  3.],
        [10., 10.,  8.,  4.],
        [ 7.,  4.,  6.,  3.],
        [ 7.,  6.,  8.,  1.]],

       [[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]]])

In [46]:
stacked_arr = da.stack([brd_example1 , brd_example2] , axis = 1)

In [47]:
stacked_arr.compute()

array([[[ 6.,  9.,  4.,  3.],
        [10., 10., 10., 10.]],

       [[10., 10.,  8.,  4.],
        [10., 10., 10., 10.]],

       [[ 7.,  4.,  6.,  3.],
        [10., 10., 10., 10.]],

       [[ 7.,  6.,  8.,  1.],
        [10., 10., 10., 10.]]])

### Concatenation 

In [48]:
concatenate_arr = da.concatenate([brd_example1 , brd_example2])

In [49]:
concatenate_arr.compute()

array([[ 6.,  9.,  4.,  3.],
       [10., 10.,  8.,  4.],
       [ 7.,  4.,  6.,  3.],
       [ 7.,  6.,  8.,  1.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [51]:
another_concatenate_arr = da.concatenate([brd_example1 , brd_example2] , axis =1)

In [52]:
another_concatenate_arr

dask.array<concatenate, shape=(4, 8), dtype=float64, chunksize=(1, 4), chunktype=numpy.ndarray>

In [53]:
another_concatenate_arr.compute()

array([[ 6.,  9.,  4.,  3., 10., 10., 10., 10.],
       [10., 10.,  8.,  4., 10., 10., 10., 10.],
       [ 7.,  4.,  6.,  3., 10., 10., 10., 10.],
       [ 7.,  6.,  8.,  1., 10., 10., 10., 10.]])

In [54]:
another_concatenate_arr = da.concatenate([brd_example1 , brd_example2] , axis =0)

In [55]:
another_concatenate_arr

dask.array<concatenate, shape=(8, 4), dtype=float64, chunksize=(1, 2), chunktype=numpy.ndarray>

In [56]:
another_concatenate_arr.compute()

array([[ 6.,  9.,  4.,  3.],
       [10., 10.,  8.,  4.],
       [ 7.,  4.,  6.,  3.],
       [ 7.,  6.,  8.,  1.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])